models/Subsidiary.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "subsidiary".
 *
 * @property integer $userNumber
 * @property integer $teachingHours
 * @property integer $suspendHours
 */
class Subsidiary extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subsidiary';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['teachingHours', 'suspendHours'], 'integer'],
            [['userNumber'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['userNumber' => 'userNumber']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'userNumber' => 'שם בת השירות',
            'teachingHours' => 'שעות הוראה',
            'suspendHours' => 'שעות שהייה',
        ];
    }

    public function getUserNumber0()
    {
        return $this->hasOne(User::className(), ['userNumber' => 'userNumber']);
    }
}

controllers/SubsidiaryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Subsidiary;
use app\models\SubsidiarySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * SubsidiaryController implements the CRUD actions for Subsidiary model.
 */
class SubsidiaryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Subsidiary models.
     * @return mixed
     */
    public function actionIndex()
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can watch subsidiary 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לצפות בבנות שירות');

        $searchModel = new SubsidiarySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Subsidiary model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can view subsidiary 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לצפות בפרטי בנות שירות');

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Subsidiary model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can create subsidiary 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לבצע פעולת יצירת בנות שירות');

        $model = new Subsidiary();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->userNumber]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Subsidiary model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can update subsidiary 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לערוך בנות שירות');

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->userNumber]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Subsidiary model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can delete subsidiary 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה להסיר בנות שירות');

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Subsidiary model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Subsidiary the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Subsidiary::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/subsidiary/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Subsidiary */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="subsidiary-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'userNumber')->dropDownList(User::getTeames2()) ?>

    <?= $form->field($model, 'teachingHours')->textInput() ?>

    <?= $form->field($model, 'suspendHours')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'יצירה' : 'שמירה', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/subsidiary/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SubsidiarySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="subsidiary-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'userNumber') ?>

    <?= $form->field($model, 'teachingHours') ?>

    <?= $form->field($model, 'suspendHours') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/subsidiary/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Subsidiary */

$this->title = 'יצירת בת שירות';
$this->params['breadcrumbs'][] = ['label' => 'בנות שירות', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subsidiary-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/subsidiary/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SubsidiarySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'בנות שירות';
$this->params['breadcrumbs'][] = $this->title;
?>
<img src="/magshimim/images/subsidiary2.jpg" class="img-rounded" height="100" width="280" style="float: left;">
<div class="subsidiary-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('יצירת בת שירות', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           [ 'attribute' => 'user', // New attribute for filter instead of fk userNumber. the functions are at TeacherSearch!
           	 'label' => 'שם בת שירות',
             'format'=>'raw',
                    'value' => function($data){
					 return
                        Html::a($data->userNumber0->fullname, ['subsidiary/view','id'=>$data->userNumber], ['title' => 'View','class'=>'no-pjax']);
                    }
            ],
            
            //'userNumber',
            'teachingHours',
            'suspendHours',

                         [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}',
        ],
        ],
    ]); ?>
</div>

views/subsidiary/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Subsidiary */

$this->title = 'עריכת בת שירות: ' . $model->userNumber0->fullName;
$this->params['breadcrumbs'][] = ['label' => 'בנות שירות', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->userNumber0->fullName, 'url' => ['view', 'id' => $model->userNumber]];
$this->params['breadcrumbs'][] = 'עריכה';
?>
<div class="subsidiary-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/subsidiary/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Subsidiary */

$this->title = $model->userNumber0->fullName;
$this->params['breadcrumbs'][] = ['label' => 'בנות שירות', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="subsidiary-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('עריכה', ['update', 'id' => $model->userNumber], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('מחיקה', ['delete', 'id' => $model->userNumber], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'האם הינך בטוח שברצונך למחוק?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'userNumber',
            [
				'attribute' => 'userNumber',
				'label' => 'שם בת השירות',
				'format' => 'raw',
				'value' => function($model){
					return $model->userNumber0->fullname;  //////////Showing subsidadiary name instead of user number.
				},
				//'filter'=>Html::dropDownList('CourseClassSearch[teacherId]', $teacher, $teachers, ['class'=>'form-control']),   //////////////// the arguments are from the controller!
			],
            'teachingHours',
            'suspendHours',
        ],
    ]) ?>

</div>