models/Assistance.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "assistance".
 *
 * @property integer $userNumber
 * @property integer $teachingHours
 * @property integer $suspendHours
 *
 * @property User $userNumber0
 */
class Assistance extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'assistance';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['teachingHours', 'suspendHours'], 'integer'],
            // [['suspendHours'], 'required'],
            [['userNumber'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['userNumber' => 'userNumber']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'userNumber' => 'שם הסייע',
            'teachingHours' => 'שעות הוראה',
            'suspendHours' => 'שעות שהייה',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserNumber0()
    {
        return $this->hasOne(User::className(), ['userNumber' => 'userNumber']);
    }
}

controllers/AssistanceController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Assistance;
use app\models\AssistanceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * AssistanceController implements the CRUD actions for Assistance model.
 */
class AssistanceController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Assistance models.
     * @return mixed
     */
    public function actionIndex()
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principal can watch assistance 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לצפות בפרטי הסייעים');

        $searchModel = new AssistanceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Assistance model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principal can view assistance 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לצפות בפרטי הסייע');

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Assistance model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principal can create assistance 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לבצע פעולת יצירת סייעים חדשים');

        $model = new Assistance();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->userNumber]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Assistance model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principal can view assistance 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לערוך פרטי סייע');

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->userNumber]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Assistance model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principal can view assistance 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה למחוק סייעים');

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Assistance model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Assistance the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Assistance::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/assistance/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Assistance */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="assistance-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'userNumber')->dropDownList(User::getTeames3()) ?>

    <?= $form->field($model, 'teachingHours')->textInput() ?>

    <?= $form->field($model, 'suspendHours')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'יצירה' : 'שמירה', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/assistance/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AssistanceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="assistance-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'userNumber') ?>

    <?= $form->field($model, 'teachingHours') ?>

    <?= $form->field($model, 'suspendHours') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/assistance/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Assistance */

$this->title = 'יצירת סייע';
$this->params['breadcrumbs'][] = ['label' => 'סייעים', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="assistance-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/assistance/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AssistanceSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'סייעים';
$this->params['breadcrumbs'][] = $this->title;
?>
<img src="/magshimim/images/assistance2.jpg" class="img-rounded" height="100" width="300" style="float: left;">
<div class="assistance-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('יצירת סייע', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'userNumber',
            [
			'attribute' => 'user', // New attribute for filter instead of fk userNumber. the functions are at TeacherSearch!
           	'label' => 'שם סייע',
            'format'=>'raw',
                    'value' => function($data){
					 return
                        Html::a($data->userNumber0->fullname, ['assistance/view','id'=>$data->userNumber], ['title' => 'View','class'=>'no-pjax']);
                    }
			],
            'teachingHours',
            'suspendHours',

                          [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}',
        ],
        ],
    ]); ?>
</div>

views/assistance/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Assistance */

$this->title = 'עריכת סייע: ' . $model->userNumber0->fullName;
$this->params['breadcrumbs'][] = ['label' => 'סייעים', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->userNumber0->fullName, 'url' => ['view', 'id' => $model->userNumber]];
$this->params['breadcrumbs'][] = 'עריכה';
?>
<div class="assistance-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/assistance/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Assistance */

$this->title = $model->userNumber0->fullName;
$this->params['breadcrumbs'][] = ['label' => 'סייעים', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="assistance-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('עריכה', ['update', 'id' => $model->userNumber], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('מחיקה', ['delete', 'id' => $model->userNumber], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'האם הינך בטוח שברצונך למחוק?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'userNumber',
            [
				'attribute' => 'userNumber',
				'label' => 'שם הסייע',
				'format' => 'raw',
				'value' => function($model){
					return $model->userNumber0->fullname;  //////////Showing assistance name instead of user number.
				},
				//'filter'=>Html::dropDownList('CourseClassSearch[teacherId]', $teacher, $teachers, ['class'=>'form-control']),   //////////////// the arguments are from the controller!
			],
            'teachingHours',
            'suspendHours',
        ],
    ]) ?>

</div>