models/Student.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use yii\helpers\ArrayHelper;
use yii\db\Query;
use yii\widgets\DetailView;
use app\models\Grade;
use \DateTime;

/**
 * This is the model class for table "student".
 *
 * @property integer $studentId
 * @property integer $studentIdOrigin
 * @property string $firstName
 * @property string $lastName
 * @property string $nickName
 * @property string $address
 * @property integer $phone
 * @property string $birth
 * @property integer $grade
 * @property string $hmo
 * @property integer $mother_phone
 * @property string $mother_address
 * @property integer $father_phone
 * @property string $father_address
 * @property string $hostel
 * @property string $hostel_contect
 * @property string $hostel_mail
 *
 * @property Grade $grade0
 */
class Student extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['studentIdOrigin', 'phone', 'grade', 'mother_phone', 'father_phone'], 'integer'],
            [['studentIdOrigin', 'nickName'], 'required'],  
            [['birth'], 'safe'],
            [['firstName', 'lastName', 'nickName'], 'match', 'pattern' => '/^[a-zA-Zא-ת0-9 -]+$/', 'message' => 'אין אפשרות להוסיף תווים מיוחדים בשדה זה, נא הזן אותיות ומספרים בלבד'],
            [['firstName', 'lastName', 'nickName', 'address', 'hmo', 'mother_address', 'father_address', 'hostel', 'hostel_contect', 'hostel_mail'], 'string', 'max' => 255],
            [['grade'], 'exist', 'skipOnError' => true, 'targetClass' => Grade::className(), 'targetAttribute' => ['grade' => 'gradeId']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'studentId' => 'מספר סטודנט',
            'studentIdOrigin' => 'תעודת זהות',
            'firstName' => 'שם פרטי',
            'lastName' => 'שם משפחה',
            'nickName' => 'כינוי',
            'address' => 'כתובת',
            'phone' => 'טלפון',
            'birth' => 'תאריך לידה',
            'grade' => 'כיתה',
            'hmo' => 'קופת חולים',
            'mother_phone' => 'טלפון אם',
            'mother_address' => 'כתובת אם',
            'father_phone' => 'טלפון אב',
            'father_address' => 'כתובת אב',
            'hostel' => 'הוסטל',
            'hostel_contect' => 'איש קשר בהוסטל',
            'hostel_mail' => 'דואר אלקטרוני בהוסטל',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrade0()
    {
        return $this->hasOne(Grade::className(), ['gradeId' => 'grade']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentactivities()
    {
        return $this->hasMany(Studentactivity::className(), ['studentId' => 'studentId']);
    }

    // This function is for gatting the student age and called in view/student.php
    function getBdayCalculation($bday)
    { 
    $datetime1 = new DateTime($bday);
    $datetime2 = new DateTime();
    $diff = $datetime1->diff($datetime2);
    return $diff->y;
    }

}

controllers/StudentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Student;
use app\models\StudentSearch;
use app\models\grade;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;

/**
 * StudentController implements the CRUD actions for Student model.
 */
class StudentController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Student models.
     * @return mixed
     */
    public function actionIndex()
    {
         //access control
		if (!\Yii::$app->user->can('indexUser')) // only teachers and principals can watch students 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לצפות ברשימת התלמידים');

        $searchModel = new StudentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'studentGrades' => Grade::getStudentGradeWithAllGrades(),    ///////////////////////////// necessary for dropdown 
			'studentGrade' => $searchModel->grade,			       ///////////////////////////// necessary for dropdown
        ]);
    }

    /**
     * Displays a single Student model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        //access control
		if (!\Yii::$app->user->can('indexUser')) // every user can view students 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לצפות בפרטי התלמיד');

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Student model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
         //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principal can create new students
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לבצע פעולת יצירת תלמידים חדשים');

        $model = new Student();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->studentId]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Student model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can update students 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה לערוך תלמידים');

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->studentId]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Student model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        //access control
		if (!\Yii::$app->user->can('fullCrudPrincipal')) // only principals can delete students 
			throw new UnauthorizedHttpException ('שלום, אינך מורשה להסיר תלמידים');

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Student model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Student the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Student::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('המשתמש לא קיים במערכת');
        }
    }
}

views/student/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Grade;
use kartik\widgets\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Student */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="student-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'studentIdOrigin')->textInput() ?>

    <?= $form->field($model, 'firstName')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'lastName')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nickName')->textInput(['placeholder' => "שם התלמיד אשר יופיע במערכת"], ['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput() ?>

    <?= $form->field($model, 'birth')->widget(DatePicker::className(), [
		//'size' => 'lg',
		'language'=>'he',
        'options' => ['placeholder' => 'בחר/י תאריך לידה'],
		'pluginOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd',
            //'todayHighlight' => true // Default today			
        ]
	]);?>

    <?= $form->field($model, 'grade')-> dropDownList(Grade::getStudentGrade()) ?>

    <?= $form->field($model, 'hmo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mother_phone')->textInput() ?>

    <?= $form->field($model, 'mother_address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'father_phone')->textInput() ?>

    <?= $form->field($model, 'father_address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hostel')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hostel_contect')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'hostel_mail')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'יצירה' : 'שמירה', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/student/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\StudentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="student-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'studentId') ?>

    <?= $form->field($model, 'studentIdOrigin') ?>

    <?= $form->field($model, 'firstName') ?>

    <?= $form->field($model, 'lastName') ?>

    <?= $form->field($model, 'nickName') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'birth') ?>

    <?php // echo $form->field($model, 'grade') ?>

    <?php // echo $form->field($model, 'hmo') ?>

    <?php // echo $form->field($model, 'mother_phone') ?>

    <?php // echo $form->field($model, 'mother_address') ?>

    <?php // echo $form->field($model, 'father_phone') ?>

    <?php // echo $form->field($model, 'father_address') ?>

    <?php // echo $form->field($model, 'hostel') ?>

    <?php // echo $form->field($model, 'hostel_contect') ?>

    <?php // echo $form->field($model, 'hostel_mail') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/student/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Student */

$this->title = 'יצירת תלמיד';
$this->params['breadcrumbs'][] = ['label' => 'תלמידים', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="יצירת תלמיד">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/student/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\StudentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'תלמידים';
$this->params['breadcrumbs'][] = $this->title;
?>
<img src="/magshimim/images/students.jpg" class="img-rounded" height="100" width="180" style="float: left;">
<div class="student-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php //access control -> hide button ?>
    <?php if (\Yii::$app->user->can('fullCrudPrincipal')) { ?>
        <p>
            <?= Html::a('יצירת תלמיד', ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    <?php } ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'studentId',
            // 'studentIdOrigin',
            // 'firstName',
            [   
                    'attribute'=>'firstName',
                    'format'=>'raw',
                    'value' => function($data)
                    {
                        return
                        Html::a($data->firstName, ['student/view','id'=>$data->studentId], ['title' => 'View','class'=>'no-pjax']);
                    }
            ],
            'lastName',
            'nickName',
            // 'address',
            // 'phone',
            // 'birth',
            // 'grade',
            [
				'attribute' => 'grade',
				//'label' => 'Student Grade',
				'format' => 'raw',
				'value' => function($model){
					return $model->grade0->gradeName;  //////////Showing role name instead of role id.
				},
				'filter'=>Html::dropDownList('StudentSearch[grade]', $studentGrade, $studentGrades, ['class'=>'form-control']),   //////////////// the arguments are from the controller!				
			],
            // 'hmo',
            // 'mother_phone',
            // 'mother_address',
            // 'father_phone',
            // 'father_address',
            // 'hostel',
            // 'hostel_contect',
            // 'hostel_mail',

            [        
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}',
        ],
        ],
    ]); ?>
</div>

views/student/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Student */

$this->title = 'עריכת תלמיד: ' . $model->studentId;
$this->params['breadcrumbs'][] = ['label' => 'תלמידים', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->studentId, 'url' => ['view', 'id' => $model->studentId]];
$this->params['breadcrumbs'][] = 'עריכה';
?>
<div class="student-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/student/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Student */

$this->title = $model->nickName;
$this->params['breadcrumbs'][] = ['label' => 'תלמידים', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php //access control -> hide button ?>
    <?php if (\Yii::$app->user->can('fullCrudPrincipal')) { ?>
    <p>
        <?= Html::a('עריכה', ['update', 'id' => $model->studentId], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('מחיקה', ['delete', 'id' => $model->studentId], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'האם הינך בטוח שברצונך למחוק?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php } ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'studentId',
            'studentIdOrigin',
            'firstName',
            'lastName',
            'nickName',
            [ // line for age, the getBdayCalculation function declared in student.php
                'attribute'=>'גיל',
				'value'=> Html::encode($model->getBdayCalculation($model->birth)),	
			],
            'address',
            'phone',
            'birth',
            // 'grade',
            [ // the grade name 
				'label' => $model->attributeLabels()['grade'],
				'value' => $model->grade0->gradeName,	
			],
            'hmo',
            'mother_phone',
            'mother_address',
            'father_phone',
            'father_address',
            'hostel',
            'hostel_contect',
            'hostel_mail',
        ],
    ]) ?>

</div>